No inviter
Wikimedia-Sverige/hostbot pull request #15
Opened 2016-12-06 09:32 UTC by BenignBeppe

I'm not sure what happened with all the commit messages, but that should be fixable in the squash.

2016-12-06 13:25 UTC, lokal-profil requested changes
Minor changes/questions but looks good overall

2016-12-06 13:25 UTC, lokal-profil commented on hb_profiles.py
> +    # NOTE: This function is no longer used for inviting, but is still
Not sure I understand. We comment this out but know it's being used? Or do you mean it is used by other Teahouse functions we might want in the future?

2016-12-06 13:25 UTC, lokal-profil commented on scripts/teahouse/send_th_invites.py
> +        settings = params
was `settings`/`profile_settings` ever used? If not this would be a good time to drop it.

2016-12-06 13:25 UTC, lokal-profil commented on scripts/teahouse/send_th_invites.py
> +    print "Invitees ({}): {}".format(len(invitees), invitees)
Add a line break and comment about this being a log message

2016-12-06 14:04 UTC, BenignBeppe commented on hb_profiles.py
> +    # NOTE: This function is no longer used for inviting, but is still
Yes, it's used for other actions, namely in: _scripts/archive/username_encoding_tester.py_, _scripts/teahouse/makeGallery.py_, _scripts/teahouse/rankHostProfiles.py_ and _scripts/twa/send_invites.py_.

2016-12-06 14:11 UTC, BenignBeppe commented on scripts/teahouse/send_th_invites.py
> +        settings = params
It was not, and is now removed.

2016-12-06 14:18 UTC, BenignBeppe commented on scripts/teahouse/send_th_invites.py
> +    print "Invitees ({}): {}".format(len(invitees), invitees)
Added line breaks.

2016-12-07 11:20 UTC, lokal-profil approved these changes

2016-12-07 11:34 UTC, merged