Variable config file
Wikimedia-Sverige/hostbot pull request #25
Opened 2017-02-17 08:12 UTC by BenignBeppe

2017-02-17 08:51 UTC, lokal-profil commented
This works fine as long as there is always a `hb_config.py` file in the directory. If you rename it and give the new name as an argument the other classes fail to find it during their import (which happens before the `imp.load_source()`.

This situation happens if you e.g. want to have `config_teahouse.py` and `config_twa.py`

2017-02-17 15:43 UTC, lokal-profil requested changes
Only minor nitpicking. Otherwise everything looks good.

2017-02-17 15:43 UTC, lokal-profil commented on config_reader.py
> +
should be two blank lines per pep8

2017-02-17 15:43 UTC, lokal-profil commented on config_reader.py
> +
should be two blank lines per pep8

2017-02-17 15:43 UTC, lokal-profil commented on config_reader.py
> +import imp
Add a short docstring. Maybe just something like:
"mechanism for dynamically loading config file/module based on command line argument"

2017-02-20 08:43 UTC, BenignBeppe commented on config_reader.py
> +import imp
Added docstrings for module and the functions.

2017-02-20 08:45 UTC, BenignBeppe commented on config_reader.py
> +
Fixed.

2017-02-20 09:14 UTC, merged